### ISSUE TITLE
Boxes next to submit don't capture text input

### ISSUE THREAD

**Issue by NickP123** [FACN3/TodoOrNot#25]
You should either remove these so the focus is on each list item or enable them to grab the information. The below is the submit error it throws when you only put text in the boxes next to submit and not anywhere else.

dom.js:172 Uncaught TypeError: Cannot read property 'value' of null
    at HTMLFormElement.<anonymous> (dom.js:172)
(anonymous) @ dom.js:172

**Comment by ionush** [comment]
this was on index.html and not mockup.html, where the code works. we will change mockup.html to index.html so the working code will reflect in index.html
