### ISSUE TITLE
If enter text then delete items in all 3 listed bullets I can't then add another item

### ISSUE THREAD

**Issue by NickP123** [FACN3/TodoOrNot#27]
Relates to text boxes next to submit not working. Having used then deleted the bullets you have supplied I am left without the option to add any new to-do's'

Below is screen shot of how it looks when I've entered then deleted each of the 3 to-do bullets given.
<img width="1373" alt="screen shot 2017-11-09 at 10 31 14" src="https://user-images.githubusercontent.com/25667270/32595604-30321b7c-c539-11e7-821a-4173b8331bc5.png">

**Comment by ionush** [comment]
this was on index.html and not mockup.html, where the code works. we will change mockup.html to index.html so the working code will reflect in index.html
